services:
  app:
    container_name: gradio-sample
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-db
    ports:
      - 7860:7860

  db:
    container_name: db-sample
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    networks:
      - app-db
    ports:
      - 3306:3306

volumes:
  mysql-data:

networks:
  app-db:
